CC = cl /nologo
LD = $(CC)
RM = del

CFLAGS = /Ox /W4 /MT

OBJS = main.obj utils.obj archive.obj extract.obj compress.obj musx.obj adpcm.obj g711.obj
EXECUTABLE = biik-tool.exe

all: $(EXECUTABLE)

$(EXECUTABLE): $(OBJS)
	$(LD) $(LDFLAGS) /Fe$@ $**

clean:
	$(RM) $(EXECUTABLE)
	$(RM) $(OBJS)
